// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamuraiApp.Shared.Data.DB;

#nullable disable

namespace SamuraiApp.Shared.Data.Migrations
{
    [DbContext(typeof(SamuraiAppContext))]
    [Migration("20250517114927_NtoN_relation_SamKen")]
    partial class NtoN_relation_SamKen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KenjutsuSamurai", b =>
                {
                    b.Property<int>("KenCollectId")
                        .HasColumnType("int");

                    b.Property<int>("SamCollectId")
                        .HasColumnType("int");

                    b.HasKey("KenCollectId", "SamCollectId");

                    b.HasIndex("SamCollectId");

                    b.ToTable("KenjutsuSamurai");
                });

            modelBuilder.Entity("SamuraiApp.Shared.Model.Kenjutsu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kenjutsu");
                });

            modelBuilder.Entity("SamuraiApp_Model.Dojo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dojo");
                });

            modelBuilder.Entity("SamuraiApp_Model.Samurai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DojoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DojoId");

                    b.ToTable("Samurai");
                });

            modelBuilder.Entity("KenjutsuSamurai", b =>
                {
                    b.HasOne("SamuraiApp.Shared.Model.Kenjutsu", null)
                        .WithMany()
                        .HasForeignKey("KenCollectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SamuraiApp_Model.Samurai", null)
                        .WithMany()
                        .HasForeignKey("SamCollectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SamuraiApp_Model.Samurai", b =>
                {
                    b.HasOne("SamuraiApp_Model.Dojo", "Dojo")
                        .WithMany()
                        .HasForeignKey("DojoId");

                    b.Navigation("Dojo");
                });
#pragma warning restore 612, 618
        }
    }
}
